language: python

env:
  - OGN_CONFIG_MODULE='config/test.py'

python:
  - 3.5
  - 3.6
  - 3.7-dev

addons:
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-9.6-postgis-2.3

before_script:
  - flake8 tests ogn_test
  - psql -U postgres -c 'CREATE DATABASE ogn_test;'
  - psql -U postgres -c 'CREATE EXTENSION postgis;'

script:
  - nosetests --with-coverage --cover-package=ogn_python
  - pip install . --upgrade
  - python -c 'import ogn_python'

after_success:
  - coveralls
